-- PROCEDENCIA DEL VÍNCULO de código de proveedor.
--
-- ── QUÉ REGISTRA ────────────────────────────────────────────────────────────
--
--   VINCULACION_MANUAL     una persona lo eligió en la pantalla de revisión.
--   APLICACION_AUTOMATICA  lo dedujo el motor y quedó guardado al APLICARSE la
--                          fila, o sea, ya se escribió un costo con él.
--
-- Son dos hechos distintos y hasta ahora no se distinguían porque todos los
-- vínculos eran humanos: `ProductoCodigoProveedor` solo se escribía al vincular
-- a mano. Desde que el macheo se guarda al aplicar conviven los dos, y el día que
-- un vínculo salga mal hay que poder saber si lo eligió alguien o lo infirió el
-- sistema — y revocar los deducidos sin tocar los humanos.
--
-- ── POR QUÉ NO SE RELLENAN LOS QUE YA ESTÁN ─────────────────────────────────
--
-- Quedan en NULO, que significa "no consta". Es cierto que hasta hoy solo la
-- vinculación manual escribía en esta tabla, pero la base también recibió datos
-- por otras vías a lo largo del tiempo y afirmar que los 317 vínculos actuales
-- fueron todos decididos por una persona sería inventar el dato que esta columna
-- existe para registrar.
--
-- El nulo además es el valor SEGURO para el uso que motivó la columna: una
-- revocación de los deducidos filtra por APLICACION_AUTOMATICA y no toca nada
-- que no conste.
--
-- Aditiva: una columna nullable. No borra ni transforma nada.

ALTER TABLE "ProductoCodigoProveedor" ADD COLUMN "origenAlta" TEXT;
