-- Cuántos renglones dice VER el lector en el papel.
--
-- ── EL AGUJERO QUE TAPA ────────────────────────────────────────────────────
--
-- Si el modelo se saltea una línea entera, la aritmética de esa línea NUNCA se
-- evalúa: las dos ecuaciones de la puerta miran las líneas que llegaron, y una
-- que no llegó no rompe ninguna. Las dos pueden cerrar con la factura
-- incompleta, y nadie se entera.
--
-- Lo señaló Emanuel mirando la factura de Mauro: los 2.000 pesos que quedaban
-- sin explicar son, muy probablemente, un renglón que no se leyó.
--
-- ── POR QUÉ ES UN CAMPO Y NO UN CÁLCULO ────────────────────────────────────
--
-- Tiene que ser una OBSERVACIÓN INDEPENDIENTE: contar los renglones impresos,
-- incluidos los que no se pudieron transcribir. Un número sacado de contar lo
-- que ya se transcribió coincide siempre consigo mismo y no controla nada.
--
-- Por eso viaja como campo propio de la lectura, se pide como tarea aparte en el
-- prompt, y se guarda AUNQUE COINCIDA: sin el número, "coincidió" y "el lector
-- no lo informó" se ven igual.

ALTER TABLE "ComprobanteProveedor" ADD COLUMN "lineasEnElPapel" INTEGER;
